package tr.org.tim.beyanname;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class beyannameDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("GTIP")
	private java.lang.String gtip;
	@org.kie.api.definition.type.Label("Dfif Belge Yüklenmesi")
	private java.lang.Boolean dfifBelge;
	@org.kie.api.definition.type.Label("İhracat Net Kg  Miktarı ")
	private java.math.BigInteger ihracatNetKgMiktar;

	@org.kie.api.definition.type.Label(value = "Hata Tespit")
	private java.lang.Boolean hata;

	public beyannameDTO() {
	}

	public java.lang.String getGtip() {
		return this.gtip;
	}

	public void setGtip(java.lang.String gtip) {
		this.gtip = gtip;
	}

	public java.lang.Boolean getDfifBelge() {
		return this.dfifBelge;
	}

	public void setDfifBelge(java.lang.Boolean dfifBelge) {
		this.dfifBelge = dfifBelge;
	}

	public java.math.BigInteger getIhracatNetKgMiktar() {
		return this.ihracatNetKgMiktar;
	}

	public void setIhracatNetKgMiktar(java.math.BigInteger ihracatNetKgMiktar) {
		this.ihracatNetKgMiktar = ihracatNetKgMiktar;
	}

	public java.lang.Boolean getHata() {
		return this.hata;
	}

	public void setHata(java.lang.Boolean hata) {
		this.hata = hata;
	}

	public beyannameDTO(java.lang.String gtip, java.lang.Boolean dfifBelge,
			java.math.BigInteger ihracatNetKgMiktar, java.lang.Boolean hata) {
		this.gtip = gtip;
		this.dfifBelge = dfifBelge;
		this.ihracatNetKgMiktar = ihracatNetKgMiktar;
		this.hata = hata;
	}

}