package tr.org.tim.beyanname;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Onay Masası 1")
@org.kie.api.definition.type.Description("Onay Masası 1")
public class onayMasasi1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Genel Sekreterlik Adı")
	private java.lang.String genelSekreterlikAdi;
	@org.kie.api.definition.type.Label(value = "Genel Sekreterlik Kodu")
	private int genelSekreterlikKod;

	public onayMasasi1() {
	}

	public java.lang.String getGenelSekreterlikAdi() {
		return this.genelSekreterlikAdi;
	}

	public void setGenelSekreterlikAdi(java.lang.String genelSekreterlikAdi) {
		this.genelSekreterlikAdi = genelSekreterlikAdi;
	}

	public int getGenelSekreterlikKod() {
		return this.genelSekreterlikKod;
	}

	public void setGenelSekreterlikKod(int genelSekreterlikKod) {
		this.genelSekreterlikKod = genelSekreterlikKod;
	}

	public onayMasasi1(java.lang.String genelSekreterlikAdi,
			int genelSekreterlikKod) {
		this.genelSekreterlikAdi = genelSekreterlikAdi;
		this.genelSekreterlikKod = genelSekreterlikKod;
	}

}